FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

COPY run_pull_email.sh /run_pull_email.sh
RUN chmod +x /run_pull_email.sh

CMD ["/run_pull_email.sh"]
