services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  pull_email:
    image: yc403/email_bot-pull_email:latest
    container_name: pull_email
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_API_URL=http://129.226.227.24:8080/generate

  process_response:
    image: yc403/email_bot-process_response:latest
    container_name: process_response
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_API_URL=http://129.226.227.24:8080/generate