version: "3.8"

services:
  pull_email:
    image: yc403/email_bot-pull_email:latest
    container_name: pull_email
    env_file:
      - .env
    network_mode: "host"
    restart: always
    # 默认docker-compose日志就是收集stdout/stderr，这里不需要特别配置

  process_response:
    image: yc403/email_bot-process_response:latest
    container_name: process_response
    env_file:
      - .env
    network_mode: "host"
    restart: always
